### ISSUE TITLE
A layer is Sequential() in cifar100_resnet18 stage1 model.

### ISSUE THREAD

**Issue by lqzhao** [anubhavashok/N2N#10]
Hi, there. When I run 
`python run.py shrinkage cifar100 teacher_models/resnet18_cifar100.net --model student_models/cifar100_resnet18_stage1.net --cuda True`
using the teacher-model and student-model you provided.  There is a error as follows:

```
Testing parent model to determine baseline accuracy
predicted 6732 out of 10000
accuracy = 67.32
Traceback (most recent call last):
  File "run.py", line 147, in <module>
    (Rs, actionSeqs, models) = rollouts(N, model, controller, architecture, dataset, e, size_constraint=size_constraint, acc_constraint=acc_constraint)
  File "/home/zlq/code/N2N/rl.py", line 126, in rollouts
    (Rs, actionSeqs, models) = rollout_batch(copy.deepcopy(model), controller, architecture, dataset, N, e, acc_constraint=acc_constraint, size_constraint=size_constraint)
  File "/home/zlq/code/N2N/rl.py", line 94, in rollout_batch
    actions = controller.rolloutActions(layers)
  File "/home/zlq/code/N2N/rl.py", line 51, in rolloutActions
    **input[i] = Layer(layers[i]).toTorchTensor(skipSupport=self.skipSupport)**
  File "/home/zlq/code/N2N/Layer.py", line 8, in __init__
    self.type = getLayerType(layer)
  File "/home/zlq/code/N2N/utils.py", line 269, in getLayerType
    return max(layerTypes.index(name), 0)
ValueError: 'Sequential' is not in list

```

I found `input[i]` is `Sequential()` in stead of a centain layer. I wonder where it comes from and how to fix it.

**Comment by anubhavashok** [comment]
Could you check whether the layers variable is generated using flattenModule?
It should un-nest the layers contained in the Sequential module.
Since Sequential is a general container that doesn't give any information about the architecture of the CNN, it is not supported as a layer type.

**Comment by lqzhao** [comment]
Thanks for your reply. 
We got an empty Sequential() after loading the student model cifar100_resnet18_stage1.net, which is one of the student models you provide. 
Specifically, 
we denote
`model`
as the student model, and 
`model._modules['layer4'][-1]`
represents the empty Squential including nothing. If we ignore this layer, it will rise an error about unequal number of actions and layers. I think that comes from the removal part.
