### ISSUE TITLE
action.reinforce(avgR - b) can't be used 

### ISSUE THREAD

**Issue by zhanghanqi** [anubhavashok/N2N#12]
Due to version problems
  the code 
         if isinstance(actions, list):
                for action in actions:
                      action.reinforce(avgR - b)
          else:
                actions.reinforce(avgR - b)
                actionloss=actionloss.mean()
has  error.
I use this code 
            if isinstance(actions, list):
                for action in actions:
                    m=torch.distributions.Categorical(probs)
                    actionloss=-m.log_prob(action)*(avgR-b)
            else:
                m = torch.distributions.Categorical(probs)
                actionloss = -m.log_prob(actions) * (avgR - b)
to instead of it.
Do these two pieces of code have the same meaning?How do I replace it if it's not the same?

**Comment by anubhavashok** [comment]
The probs variable should be unique for each action, so this won't work correctly.
However, you can save the log_probs along with each action.

So the code will look something like:
```
for action, log_prob in actions:
  actionLoss += log_prob * (avgR - b)
```

Also see https://github.com/pytorch/examples/blob/master/reinforcement_learning/reinforce.py#L58 as a possible reference implementation
