### ISSUE TITLE
lookup table values

### ISSUE THREAD

**Issue by jangkyung** [anubhavashok/N2N#3]
lookup = [0.25 , .5, .5, .5, .5, .5, .6, .7, .8, .9, 1.] is the layer shrinkage parameters in the code. This is not the same as the description in the paper. Would you please explain the difference?

**Comment by anubhavashok** [comment]
The lookup table would need to be trained based on the teacher model for best results.
You can try the default values explained in the paper and can modify the distribution of shrinkage values if you get too many degenerate models.
