### ISSUE TITLE
the pre-trained model 

### ISSUE THREAD

**Issue by LANMNG** [anubhavashok/N2N#7]
which framwork is the pre-trained model trained? pytorch or caffe,  and how can i train a teacher model by myself? such as res50 and densenet @anubhavashok

**Comment by anubhavashok** [comment]
It is in pytorch.
If you would like to train your own model, the dataset folder and utils file have code for training models.
ResNet50 should work in the current code but there is no support for densenet.
If you'd like to try custom architectures, do refer to the paper on how to design the representation and suggestions about what should constitute a degenerate architecture.
